### ISSUE TITLE
Where can I download the amp and amp_share files from?

### ISSUE THREAD

**Issue by ainsofs** [Acosix/alfresco-audit#1]
Where can I download the amp and amp_share files from so that I can install and trial your module?

Thanks,

**Comment by maciass2008** [comment]
hi,
you can do that by downloading the project code source then using maven to build the project and generate the .amp file

**Comment by AFaust** [comment]
Somehow I had missed that question. The pre-built AMP is also available from Maven Central. Check the [relevant README section](https://github.com/Acosix/alfresco-audit#maven-usage) for how to use it in Maven - you can use [search.maven.org](https://search.maven.org/search?q=g:de.acosix.alfresco.audit) to download the AMP manually. Note that there is no Share AMP for this extension.
