### ISSUE TITLE
Return firstLogin and lastLogin in inactive user query?

### ISSUE THREAD

**Issue by jeremyscrivener** [Acosix/alfresco-audit#2]
Hi Axel,

Firstly, thanks for the audit plugin.

I have a use case where I want to use the inactive user query, but also return the lastlogin time for each inactive user.

I've tried adding these to the results for an inactive user query, however they all seem to return an epoch-like time (1970-01-01).

Is it possible to return these values for inactive users? Or (if not) is this the reason why those values are only returned in your active query results?

Regards,
Jeremy

**Comment by AFaust** [comment]
The reason that the last login time is not returned for inactive users is simply that no "last login" was found in the audit data for the time frame examined for activity. It would certainly be possible to include a last login time also for inactive users, which would require an additional audit query operation to obtain the last login time before the examined period. The [batch operation](https://github.com/Acosix/alfresco-audit/blob/master/src/main/java/de/acosix/alfresco/audit/repo/batch/PersonAuditWorker.java#L226) for checking each user would be the place to enhance (in addition to the handling of the web script response)

**Comment by jeremyscrivener** [comment]
Thanks for the pointer!

**Comment by AFaust** [comment]
Closing issue after period of inactivity - the base operation will not be enhanced to retrieve a "last login" timestamp outside of the time period of the query as that would significantly affect performance of the operation.
