### ISSUE TITLE
Disabling to user auditing capabilities

### ISSUE THREAD

**Issue by binduwavell** [Acosix/alfresco-audit#3]
I'm using the following to disable the audit applications, the audit listener and the jobs for managing these items:

```
audit.acosix-audit-activeuserlogin.enabled=false
audit.acosix-audit-activeusers.enabled=false
acosix-audit.auth.listener.enabled=false
acosix-audit.job.consolidateActiveUsersAudit.cron=* * * * * ? 2099
acosix-audit.job.activeUserLoginCleanup.cron=* * * * * ? 2099
acosix-audit.job.activeUsersCleanup.cron=* * * * * ? 2099
```
***Updated based on Axel's comment about the properties being lower cased***

Thanks for your help, I'm creating an issue in case there is more that should be disabled and so you can share this with others if they are interested. No real ask here :) feel free to close.

**Comment by binduwavell** [comment]
There might be an issue here. I'm using an SDK project ([yoalf.zip](https://github.com/Acosix/alfresco-audit/files/4411947/yoalf.zip)). The audit applications are not disabled and `acosix-audit-activeUserLogin` fills in with audit events, which I think implies that  `acosix-audit.auth.listener.enabled=false` is also not doing the expected.

Using this command to list audit applications and their enabled state:
```
curl -u admin:admin "http://localhost:8080/alfresco/service/api/audit/control" | jq
```

Sample output:
```
{
  "enabled": true,
  "applications": [
    {
      "name": "Alfresco Tagging Service",
      "path": "/tagging",
      "enabled": true
    },
    {
      "name": "acosix-audit-activeUserLogin",
      "path": "/acosix-audit-activeUserLogin",
      "enabled": true
    },
    {
      "name": "acosix-audit-activeUsers",
      "path": "/acosix-audit-activeUsers",
      "enabled": true
    }
  ]
}
```

Using this command to check the audit entries (it also logs a new login event):
```
curl -u admin:admin "http://localhost:8080/alfresco/service/api/audit/query/acosix-audit-activeUserLogin" | jq
```

Using the OOTB Support Tools which is included in the project the System Information tool shows these properties as having been set correctly. i.e. enabled=false. 

Also, interestingly the Scheduled Jobs tool  shows the cron expressions for the jobs as having been updated.

I can disable the audit application with:
```
curl -u admin:admin -d "" "http://localhost:8080/alfresco/service/api/audit/control/acosix-audit-activeUserLogin/acosix-audit-activeUserLogin?enable=false" | jq
```
And subsequent curl calls to query the application will not add new entries.

**Comment by AFaust** [comment]
So I have checked (debugged) the authentication listener(s) with the configuration, and they don't trigger as expected. I say "as expected" because without installing the "full" alfresco-utility module, they cannot be called at all even if enabled, as these require the [AuthenticationListenersFacade](https://github.com/Acosix/alfresco-utility/blob/master/full/repository/src/main/java/de/acosix/alfresco/utility/repo/web/auth/AuthenticationListenersFacade.java) to replace the default listener(s) via Spring post processor patches only available in the full module (as a rule, patches changing default beans are only part of the full module).

And through debugging I have found why the audit application could not be disabled by setting the enabled properties to false. The lookup that Alfresco performs for the properties is lower-casing the application ID. Thus the proper properties must be set as
```
audit.acosix-audit-activeuserlogin.enabled=false
audit.acosix-audit-activeusers.enabled=false
```

**Comment by binduwavell** [comment]
Thanks much Axel!

I'm curious is it expected that the `acosix-audit-activeUserLogin` audit application will still fill in if `acosix-audit.auth.listener.enabled=false`? I'll go read through the audit config XML again... I guess I still don't fully grok how the two audit apps work in this addon.

**Comment by AFaust** [comment]
Regular logins via the AuthenticationService will still fill in even if listeners are disabled. This is done via the alfresco-api audit producer.

**Comment by AFaust** [comment]
The two audit applications are used differently for short-term and long term storage. The short term records every individual login, while the long-term aggregates those logins to "time frames of being active". This is done with an eye on German (European) privacy concerns, e.g. in Germany it is illegal to profile / monitor employees work behaviour in high granularity, and record data that would allow reverse analysis of work patterns down to minutes / seconds etc. For that reason, the short-term audit entries are deleted as soon as possible based on the aggregation configuration.

**Comment by AFaust** [comment]
Closing issue after period of inactivity
